"""Allow NULL ELO

Revision ID: 3e21001167f2
Revises: bb0f848ca4d9
Create Date: 2026-02-02 02:15:55.954999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e21001167f2'
down_revision: Union[str, Sequence[str], None] = 'bb0f848ca4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipo_rating_actual', 'elo_actual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               schema='futsim')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipo_rating_actual', 'elo_actual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               schema='futsim')
    # ### end Alembic commands ###
