"""Initial_migration

Revision ID: 0da9395eac16
Revises: 
Create Date: 2026-02-01 17:19:53.986356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0da9395eac16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_competencia_tipo',
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tipo_id'),
    sa.UniqueConstraint('codigo'),
    schema='futsim'
    )
    op.create_index(op.f('ix_futsim_cat_competencia_tipo_tipo_id'), 'cat_competencia_tipo', ['tipo_id'], unique=False, schema='futsim')
    op.create_table('cat_estado_generico',
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('estado_id'),
    sa.UniqueConstraint('codigo'),
    schema='futsim'
    )
    op.create_index(op.f('ix_futsim_cat_estado_generico_estado_id'), 'cat_estado_generico', ['estado_id'], unique=False, schema='futsim')
    op.create_table('cat_etapa_tipo',
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tipo_id'),
    sa.UniqueConstraint('codigo'),
    schema='futsim'
    )
    op.create_index(op.f('ix_futsim_cat_etapa_tipo_tipo_id'), 'cat_etapa_tipo', ['tipo_id'], unique=False, schema='futsim')
    op.create_table('cat_metodo_clasificacion',
    sa.Column('metodo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('metodo_id'),
    sa.UniqueConstraint('codigo'),
    schema='futsim'
    )
    op.create_index(op.f('ix_futsim_cat_metodo_clasificacion_metodo_id'), 'cat_metodo_clasificacion', ['metodo_id'], unique=False, schema='futsim')
    op.create_table('media_asset',
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('ancho', sa.Integer(), nullable=True),
    sa.Column('alto', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('media_id'),
    schema='futsim'
    )
    op.create_table('mundo',
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_actual', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('semilla_rng', sa.BigInteger(), nullable=True),
    sa.Column('configuracion_global', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('mundo_id'),
    schema='futsim'
    )
    op.create_table('perfil_climatico',
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('codigo_koppen', sa.String(length=5), nullable=True),
    sa.Column('temp_promedio_verano', sa.Float(), nullable=True),
    sa.Column('temp_promedio_invierno', sa.Float(), nullable=True),
    sa.Column('altitud_media', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('ventaja_local_climatica', sa.Float(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('perfil_id'),
    schema='futsim'
    )
    op.create_table('perfil_sorteo',
    sa.Column('perfil_sorteo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('perfil_sorteo_id'),
    sa.UniqueConstraint('nombre'),
    schema='futsim'
    )
    op.create_table('confederacion',
    sa.Column('confederacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('acronimo', sa.String(length=10), nullable=True),
    sa.Column('logo_media_id', sa.UUID(), nullable=True),
    sa.Column('reputacion_base', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['logo_media_id'], ['futsim.media_asset.media_id'], ),
    sa.PrimaryKeyConstraint('confederacion_id'),
    sa.UniqueConstraint('acronimo'),
    sa.UniqueConstraint('nombre'),
    schema='futsim'
    )
    op.create_table('estadistica_global',
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('total_goles', sa.Integer(), nullable=False),
    sa.Column('promedio_goles_partido', sa.Float(), nullable=False),
    sa.Column('partidos_jugados', sa.Integer(), nullable=False),
    sa.Column('distribucion_elo', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['mundo_id'], ['futsim.mundo.mundo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stat_id'),
    sa.UniqueConstraint('mundo_id', 'fecha'),
    schema='futsim'
    )
    op.create_table('mundo_snapshot',
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tick', sa.BigInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mundo_id'], ['futsim.mundo.mundo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('mundo_id', 'fecha', 'tick'),
    schema='futsim'
    )
    op.create_table('sim_log',
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.BigInteger(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mundo_id'], ['futsim.mundo.mundo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id'),
    schema='futsim'
    )
    op.create_table('temporada',
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('es_actual', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['mundo_id'], ['futsim.mundo.mundo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('temporada_id'),
    sa.UniqueConstraint('mundo_id', 'nombre'),
    schema='futsim'
    )
    op.create_table('pais',
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('confederacion_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('gentilicio', sa.String(length=50), nullable=True),
    sa.Column('bandera_media_id', sa.UUID(), nullable=True),
    sa.Column('nivel_futbolistico', sa.Integer(), nullable=False),
    sa.Column('poblacion', sa.BigInteger(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('nivel_futbolistico BETWEEN 1 AND 100', name='ck_pais_nivel'),
    sa.ForeignKeyConstraint(['bandera_media_id'], ['futsim.media_asset.media_id'], ),
    sa.ForeignKeyConstraint(['confederacion_id'], ['futsim.confederacion.confederacion_id'], ),
    sa.PrimaryKeyConstraint('pais_id'),
    sa.UniqueConstraint('iso_code'),
    sa.UniqueConstraint('nombre'),
    schema='futsim'
    )
    op.create_table('asociacion',
    sa.Column('asociacion_id', sa.Integer(), nullable=False),
    sa.Column('confederacion_id', sa.Integer(), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('acronimo', sa.String(length=20), nullable=True),
    sa.Column('logo_media_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['confederacion_id'], ['futsim.confederacion.confederacion_id'], ),
    sa.ForeignKeyConstraint(['logo_media_id'], ['futsim.media_asset.media_id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['futsim.pais.pais_id'], ),
    sa.PrimaryKeyConstraint('asociacion_id'),
    sa.UniqueConstraint('confederacion_id', 'nombre'),
    schema='futsim'
    )
    op.create_table('region',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_region', sa.String(length=50), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['futsim.pais.pais_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('region_id'),
    sa.UniqueConstraint('pais_id', 'nombre'),
    schema='futsim'
    )
    op.create_table('ciudad',
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('perfil_climatico_id', sa.Integer(), nullable=True),
    sa.Column('coordenadas', sa.String(), nullable=True),
    sa.Column('poblacion', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['perfil_climatico_id'], ['futsim.perfil_climatico.perfil_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['futsim.region.region_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ciudad_id'),
    sa.UniqueConstraint('region_id', 'nombre'),
    schema='futsim'
    )
    op.create_table('competencia',
    sa.Column('competencia_id', sa.Integer(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('confederacion_id', sa.Integer(), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('asociacion_id', sa.Integer(), nullable=True),
    sa.Column('logo_media_id', sa.UUID(), nullable=True),
    sa.Column('reputacion_base', sa.Integer(), nullable=False),
    sa.Column('configuracion_base', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['asociacion_id'], ['futsim.asociacion.asociacion_id'], ),
    sa.ForeignKeyConstraint(['confederacion_id'], ['futsim.confederacion.confederacion_id'], ),
    sa.ForeignKeyConstraint(['logo_media_id'], ['futsim.media_asset.media_id'], ),
    sa.ForeignKeyConstraint(['mundo_id'], ['futsim.mundo.mundo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pais_id'], ['futsim.pais.pais_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['futsim.region.region_id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['futsim.cat_competencia_tipo.tipo_id'], ),
    sa.PrimaryKeyConstraint('competencia_id'),
    sa.UniqueConstraint('mundo_id', 'nombre'),
    schema='futsim'
    )
    op.create_table('competencia_edicion',
    sa.Column('edicion_id', sa.Integer(), nullable=False),
    sa.Column('competencia_id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('nombre_display', sa.String(length=100), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('reglas_edicion', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint("estado IN ('PROGRAMADA','EN_CURSO','FINALIZADA')"),
    sa.ForeignKeyConstraint(['competencia_id'], ['futsim.competencia.competencia_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temporada_id'], ['futsim.temporada.temporada_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edicion_id'),
    sa.UniqueConstraint('competencia_id', 'temporada_id'),
    schema='futsim'
    )
    op.create_table('competencia_reputacion',
    sa.Column('competencia_id', sa.Integer(), nullable=False),
    sa.Column('alcance', sa.String(length=20), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("alcance IN ('WORLD','CONFED','PAIS')"),
    sa.ForeignKeyConstraint(['competencia_id'], ['futsim.competencia.competencia_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temporada_id'], ['futsim.temporada.temporada_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('competencia_id', 'alcance', 'temporada_id'),
    schema='futsim'
    )
    op.create_table('estadio',
    sa.Column('estadio_id', sa.Integer(), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('tipo_cesped', sa.String(length=50), nullable=True),
    sa.Column('foto_media_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['ciudad_id'], ['futsim.ciudad.ciudad_id'], ),
    sa.ForeignKeyConstraint(['foto_media_id'], ['futsim.media_asset.media_id'], ),
    sa.PrimaryKeyConstraint('estadio_id'),
    schema='futsim'
    )
    op.create_table('noticia',
    sa.Column('noticia_id', sa.BigInteger(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titular', sa.String(length=200), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=True),
    sa.Column('equipos_relacionados', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('competencia_id', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['competencia_id'], ['futsim.competencia.competencia_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mundo_id'], ['futsim.mundo.mundo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('noticia_id'),
    schema='futsim'
    )
    op.create_table('regla_clasificacion',
    sa.Column('clasificacion_id', sa.Integer(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=True),
    sa.Column('competencia_fuente_id', sa.Integer(), nullable=False),
    sa.Column('etapa_fuente_tipo', sa.String(length=30), nullable=True),
    sa.Column('grupo_fuente_codigo', sa.String(length=10), nullable=True),
    sa.Column('posicion_desde', sa.Integer(), nullable=True),
    sa.Column('posicion_hasta', sa.Integer(), nullable=True),
    sa.Column('condicion_fuente', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('competencia_destino_id', sa.Integer(), nullable=False),
    sa.Column('etapa_destino_tipo', sa.String(length=30), nullable=True),
    sa.Column('hint_ronda_destino', sa.String(length=30), nullable=True),
    sa.Column('metodo_id', sa.Integer(), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competencia_destino_id'], ['futsim.competencia.competencia_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competencia_fuente_id'], ['futsim.competencia.competencia_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metodo_id'], ['futsim.cat_metodo_clasificacion.metodo_id'], ),
    sa.ForeignKeyConstraint(['mundo_id'], ['futsim.mundo.mundo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temporada_id'], ['futsim.temporada.temporada_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clasificacion_id'),
    schema='futsim'
    )
    op.create_table('regla_elegibilidad',
    sa.Column('elegibilidad_id', sa.Integer(), nullable=False),
    sa.Column('competencia_id', sa.Integer(), nullable=False),
    sa.Column('regla', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competencia_id'], ['futsim.competencia.competencia_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('elegibilidad_id'),
    schema='futsim'
    )
    op.create_table('sistema_ranking',
    sa.Column('sistema_id', sa.Integer(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('alcance', sa.String(length=30), nullable=False),
    sa.Column('ventana_anios', sa.Integer(), nullable=False),
    sa.Column('reglas_calculo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confederacion_id', sa.Integer(), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('competencia_id', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint("alcance IN ('WORLD','CONFED','PAIS','COMPETENCIA')"),
    sa.CheckConstraint('ventana_anios BETWEEN 1 AND 20'),
    sa.ForeignKeyConstraint(['competencia_id'], ['futsim.competencia.competencia_id'], ),
    sa.ForeignKeyConstraint(['confederacion_id'], ['futsim.confederacion.confederacion_id'], ),
    sa.ForeignKeyConstraint(['mundo_id'], ['futsim.mundo.mundo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pais_id'], ['futsim.pais.pais_id'], ),
    sa.PrimaryKeyConstraint('sistema_id'),
    sa.UniqueConstraint('mundo_id', 'nombre'),
    schema='futsim'
    )
    op.create_table('equipo',
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_tla', sa.String(length=10), nullable=True),
    sa.Column('anio_fundacion', sa.Integer(), nullable=True),
    sa.Column('ciudad_sede_id', sa.Integer(), nullable=True),
    sa.Column('pais_origen_id', sa.Integer(), nullable=True),
    sa.Column('asociacion_liga_id', sa.Integer(), nullable=True),
    sa.Column('estadio_principal_id', sa.Integer(), nullable=True),
    sa.Column('escudo_media_id', sa.UUID(), nullable=True),
    sa.Column('colores', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['asociacion_liga_id'], ['futsim.asociacion.asociacion_id'], ),
    sa.ForeignKeyConstraint(['ciudad_sede_id'], ['futsim.ciudad.ciudad_id'], ),
    sa.ForeignKeyConstraint(['escudo_media_id'], ['futsim.media_asset.media_id'], ),
    sa.ForeignKeyConstraint(['estadio_principal_id'], ['futsim.estadio.estadio_id'], ),
    sa.ForeignKeyConstraint(['mundo_id'], ['futsim.mundo.mundo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pais_origen_id'], ['futsim.pais.pais_id'], ),
    sa.PrimaryKeyConstraint('equipo_id'),
    sa.UniqueConstraint('mundo_id', 'nombre'),
    schema='futsim'
    )
    op.create_table('etapa',
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('edicion_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('config_etapa', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('perfil_sorteo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edicion_id'], ['futsim.competencia_edicion.edicion_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfil_sorteo_id'], ['futsim.perfil_sorteo.perfil_sorteo_id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['futsim.cat_etapa_tipo.tipo_id'], ),
    sa.PrimaryKeyConstraint('etapa_id'),
    sa.UniqueConstraint('edicion_id', 'orden'),
    schema='futsim'
    )
    op.create_table('regla_asignacion_cupos',
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('competencia_objetivo_id', sa.Integer(), nullable=False),
    sa.Column('sistema_id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=True),
    sa.Column('regla', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competencia_objetivo_id'], ['futsim.competencia.competencia_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mundo_id'], ['futsim.mundo.mundo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sistema_id'], ['futsim.sistema_ranking.sistema_id'], ),
    sa.ForeignKeyConstraint(['temporada_id'], ['futsim.temporada.temporada_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asignacion_id'),
    schema='futsim'
    )
    op.create_table('equipo_elo_hist',
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('elo', sa.Float(), nullable=False),
    sa.Column('potencial_basal', sa.Integer(), nullable=False),
    sa.Column('volatilidad', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equipo_id', 'fecha'),
    schema='futsim'
    )
    op.create_table('equipo_estadio_hist',
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('estadio_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('motivo', sa.String(length=100), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estadio_id'], ['futsim.estadio.estadio_id'], ),
    sa.PrimaryKeyConstraint('equipo_id', 'estadio_id', 'fecha_inicio'),
    schema='futsim'
    )
    op.create_table('equipo_finanzas',
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('presupuesto_fichajes', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('presupuesto_salarial', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('deuda_total', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('poder_economico_base', sa.Integer(), nullable=False),
    sa.Column('tipo_propiedad', sa.String(length=50), nullable=True),
    sa.Column('paciencia_directiva', sa.Integer(), nullable=False),
    sa.Column('actualizado_en', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('paciencia_directiva BETWEEN 1 AND 20'),
    sa.CheckConstraint('poder_economico_base BETWEEN 1 AND 20'),
    sa.ForeignKeyConstraint(['equipo_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equipo_id'),
    schema='futsim'
    )
    op.create_table('equipo_institucion',
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('potencial_basal', sa.Integer(), nullable=False),
    sa.Column('volatilidad', sa.Integer(), nullable=False),
    sa.Column('infraestructura', sa.Integer(), nullable=False),
    sa.Column('nivel_scouting', sa.Integer(), nullable=False),
    sa.Column('nivel_entrenamiento', sa.Integer(), nullable=False),
    sa.Column('nivel_juveniles', sa.Integer(), nullable=False),
    sa.Column('estabilidad_directiva', sa.Integer(), nullable=False),
    sa.Column('hinchada', sa.Integer(), nullable=False),
    sa.Column('reputacion_historica', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('estabilidad_directiva BETWEEN 1 AND 20'),
    sa.CheckConstraint('infraestructura BETWEEN 1 AND 20'),
    sa.CheckConstraint('nivel_entrenamiento BETWEEN 1 AND 20'),
    sa.CheckConstraint('nivel_juveniles BETWEEN 1 AND 20'),
    sa.CheckConstraint('nivel_scouting BETWEEN 1 AND 20'),
    sa.CheckConstraint('volatilidad BETWEEN 1 AND 100'),
    sa.ForeignKeyConstraint(['equipo_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equipo_id'),
    schema='futsim'
    )
    op.create_table('equipo_rating_actual',
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('elo_actual', sa.Float(), nullable=False),
    sa.Column('ataque', sa.Integer(), nullable=False),
    sa.Column('defensa', sa.Integer(), nullable=False),
    sa.Column('mediocampo', sa.Integer(), nullable=False),
    sa.Column('moral', sa.Integer(), nullable=False),
    sa.Column('fatiga', sa.Integer(), nullable=False),
    sa.Column('cohesion', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.Integer(), nullable=False),
    sa.Column('tactica', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ataque BETWEEN 1 AND 100'),
    sa.CheckConstraint('cohesion BETWEEN 0 AND 100'),
    sa.CheckConstraint('defensa BETWEEN 1 AND 100'),
    sa.CheckConstraint('disciplina BETWEEN 0 AND 100'),
    sa.CheckConstraint('fatiga BETWEEN 0 AND 100'),
    sa.CheckConstraint('mediocampo BETWEEN 1 AND 100'),
    sa.CheckConstraint('moral BETWEEN 0 AND 100'),
    sa.ForeignKeyConstraint(['equipo_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equipo_id'),
    schema='futsim'
    )
    op.create_table('evento_equipo',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('severidad', sa.Integer(), nullable=False),
    sa.Column('modificadores', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.CheckConstraint('severidad BETWEEN 1 AND 10'),
    sa.ForeignKeyConstraint(['equipo_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mundo_id'], ['futsim.mundo.mundo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evento_id'),
    schema='futsim'
    )
    op.create_table('grupo',
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['futsim.etapa.etapa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_id'),
    sa.UniqueConstraint('etapa_id', 'codigo'),
    schema='futsim'
    )
    op.create_table('historia_narrativa',
    sa.Column('historia_id', sa.Integer(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_generacion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('importancia', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('competencia_id', sa.Integer(), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('resumen_texto', sa.Text(), nullable=True),
    sa.Column('datos_clave', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('importancia BETWEEN 1 AND 10'),
    sa.ForeignKeyConstraint(['competencia_id'], ['futsim.competencia.competencia_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipo_id'], ['futsim.equipo.equipo_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mundo_id'], ['futsim.mundo.mundo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pais_id'], ['futsim.pais.pais_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('historia_id'),
    schema='futsim'
    )
    op.create_table('historial_enfrentamiento',
    sa.Column('historial_id', sa.Integer(), nullable=False),
    sa.Column('equipo_a_id', sa.Integer(), nullable=False),
    sa.Column('equipo_b_id', sa.Integer(), nullable=False),
    sa.Column('partidos_jugados', sa.Integer(), nullable=False),
    sa.Column('victorias_a', sa.Integer(), nullable=False),
    sa.Column('victorias_b', sa.Integer(), nullable=False),
    sa.Column('empates', sa.Integer(), nullable=False),
    sa.Column('goles_a', sa.Integer(), nullable=False),
    sa.Column('goles_b', sa.Integer(), nullable=False),
    sa.Column('ultimo_partido_fecha', sa.Date(), nullable=True),
    sa.Column('ultimo_ganador_id', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('equipo_a_id < equipo_b_id'),
    sa.ForeignKeyConstraint(['equipo_a_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipo_b_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ultimo_ganador_id'], ['futsim.equipo.equipo_id'], ),
    sa.PrimaryKeyConstraint('historial_id'),
    sa.UniqueConstraint('equipo_a_id', 'equipo_b_id'),
    schema='futsim'
    )
    op.create_table('ranking_entrada',
    sa.Column('entrada_id', sa.BigInteger(), nullable=False),
    sa.Column('sistema_id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=True),
    sa.Column('at_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('confederacion_id', sa.Integer(), nullable=True),
    sa.Column('competencia_id', sa.Integer(), nullable=True),
    sa.Column('puntos_totales', sa.Float(), nullable=False),
    sa.Column('ranking_posicion', sa.Integer(), nullable=True),
    sa.Column('historial_puntos', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('\n            (CASE WHEN equipo_id IS NULL THEN 0 ELSE 1 END) +\n            (CASE WHEN pais_id IS NULL THEN 0 ELSE 1 END) +\n            (CASE WHEN confederacion_id IS NULL THEN 0 ELSE 1 END) +\n            (CASE WHEN competencia_id IS NULL THEN 0 ELSE 1 END) = 1\n        ', name='ck_ranking_polymorphic'),
    sa.ForeignKeyConstraint(['competencia_id'], ['futsim.competencia.competencia_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confederacion_id'], ['futsim.confederacion.confederacion_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipo_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pais_id'], ['futsim.pais.pais_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sistema_id'], ['futsim.sistema_ranking.sistema_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temporada_id'], ['futsim.temporada.temporada_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entrada_id'),
    schema='futsim'
    )
    op.create_table('rivalidad',
    sa.Column('rivalidad_id', sa.Integer(), nullable=False),
    sa.Column('equipo_a_id', sa.Integer(), nullable=False),
    sa.Column('equipo_b_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('intensidad', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('equipo_a_id < equipo_b_id'),
    sa.CheckConstraint('intensidad BETWEEN 0 AND 100'),
    sa.ForeignKeyConstraint(['equipo_a_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipo_b_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rivalidad_id'),
    sa.UniqueConstraint('equipo_a_id', 'equipo_b_id'),
    schema='futsim'
    )
    op.create_table('snapshot_equipo',
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('elo', sa.Float(), nullable=True),
    sa.Column('reputacion', sa.Integer(), nullable=True),
    sa.Column('presupuesto_fichajes', sa.Float(), nullable=True),
    sa.Column('presupuesto_salarial', sa.Float(), nullable=True),
    sa.Column('posicion_estimada', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('equipo_id', 'fecha'),
    schema='futsim'
    )
    op.create_table('participante',
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('edicion_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('metodo_id', sa.Integer(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('bombo_sorteo', sa.Integer(), nullable=True),
    sa.Column('grupo_id_inicial', sa.Integer(), nullable=True),
    sa.Column('grupo_inicial_texto', sa.String(length=10), nullable=True),
    sa.Column('posicion_final', sa.Integer(), nullable=True),
    sa.Column('ronda_eliminacion', sa.String(length=50), nullable=True),
    sa.Column('puntos_ranking_ganados', sa.Float(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['edicion_id'], ['futsim.competencia_edicion.edicion_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipo_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id_inicial'], ['futsim.grupo.grupo_id'], ),
    sa.ForeignKeyConstraint(['metodo_id'], ['futsim.cat_metodo_clasificacion.metodo_id'], ),
    sa.PrimaryKeyConstraint('participante_id'),
    sa.UniqueConstraint('edicion_id', 'equipo_id'),
    schema='futsim'
    )
    op.create_table('ronda',
    sa.Column('ronda_id', sa.Integer(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('pierna', sa.Integer(), nullable=False),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['futsim.etapa.etapa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['futsim.grupo.grupo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ronda_id'),
    sa.UniqueConstraint('etapa_id', 'grupo_id', 'numero', 'pierna'),
    schema='futsim'
    )
    op.create_table('tabla_posiciones',
    sa.Column('edicion_id', sa.Integer(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('pj', sa.Integer(), nullable=False),
    sa.Column('pg', sa.Integer(), nullable=False),
    sa.Column('pe', sa.Integer(), nullable=False),
    sa.Column('pp', sa.Integer(), nullable=False),
    sa.Column('gf', sa.Integer(), nullable=False),
    sa.Column('gc', sa.Integer(), nullable=False),
    sa.Column('dg', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=False),
    sa.Column('forma', sa.String(length=10), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['edicion_id'], ['futsim.competencia_edicion.edicion_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipo_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['etapa_id'], ['futsim.etapa.etapa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['futsim.grupo.grupo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edicion_id', 'etapa_id', 'grupo_id', 'equipo_id'),
    schema='futsim'
    )
    op.create_table('partido',
    sa.Column('partido_id', sa.BigInteger(), nullable=False),
    sa.Column('edicion_id', sa.Integer(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('ronda_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('local_equipo_id', sa.Integer(), nullable=False),
    sa.Column('visita_equipo_id', sa.Integer(), nullable=False),
    sa.Column('estadio_real_id', sa.Integer(), nullable=True),
    sa.Column('es_neutral', sa.Boolean(), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('jornada', sa.Integer(), nullable=True),
    sa.Column('fase_label', sa.String(length=50), nullable=True),
    sa.Column('asistencia', sa.Integer(), nullable=True),
    sa.Column('goles_local', sa.Integer(), nullable=True),
    sa.Column('goles_visita', sa.Integer(), nullable=True),
    sa.Column('penales_local', sa.Integer(), nullable=True),
    sa.Column('penales_visita', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('reporte_motor', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint("estado IN ('PENDIENTE','SIMULADO','JUGADO')"),
    sa.CheckConstraint('local_equipo_id <> visita_equipo_id'),
    sa.ForeignKeyConstraint(['ciudad_id'], ['futsim.ciudad.ciudad_id'], ),
    sa.ForeignKeyConstraint(['edicion_id'], ['futsim.competencia_edicion.edicion_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estadio_real_id'], ['futsim.estadio.estadio_id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['futsim.etapa.etapa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['futsim.grupo.grupo_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['local_equipo_id'], ['futsim.equipo.equipo_id'], ),
    sa.ForeignKeyConstraint(['ronda_id'], ['futsim.ronda.ronda_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visita_equipo_id'], ['futsim.equipo.equipo_id'], ),
    sa.PrimaryKeyConstraint('partido_id'),
    schema='futsim'
    )
    op.create_table('partido_clima',
    sa.Column('partido_id', sa.BigInteger(), nullable=False),
    sa.Column('temperatura_c', sa.Float(), nullable=True),
    sa.Column('humedad', sa.Float(), nullable=True),
    sa.Column('viento_kmh', sa.Float(), nullable=True),
    sa.Column('lluvia_mm', sa.Float(), nullable=True),
    sa.Column('condicion', sa.String(length=30), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['partido_id'], ['futsim.partido.partido_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partido_id'),
    schema='futsim'
    )
    op.create_table('partido_contexto',
    sa.Column('partido_id', sa.BigInteger(), nullable=False),
    sa.Column('intensidad_hinchada', sa.Integer(), nullable=False),
    sa.Column('viaje_km_visita', sa.Integer(), nullable=True),
    sa.Column('altitud_m', sa.Integer(), nullable=True),
    sa.Column('rivalidad_intensidad', sa.Integer(), nullable=True),
    sa.Column('presion', sa.Integer(), nullable=False),
    sa.Column('external', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('intensidad_hinchada BETWEEN 0 AND 100'),
    sa.CheckConstraint('presion BETWEEN 0 AND 100'),
    sa.ForeignKeyConstraint(['partido_id'], ['futsim.partido.partido_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partido_id'),
    schema='futsim'
    )
    op.create_table('partido_stats_equipo',
    sa.Column('partido_id', sa.BigInteger(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('es_local', sa.Boolean(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('tiros', sa.Integer(), nullable=True),
    sa.Column('tiros_arco', sa.Integer(), nullable=True),
    sa.Column('posesion', sa.Float(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('faltas', sa.Integer(), nullable=True),
    sa.Column('amarillas', sa.Integer(), nullable=True),
    sa.Column('rojas', sa.Integer(), nullable=True),
    sa.Column('delta_elo', sa.Float(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['futsim.equipo.equipo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partido_id'], ['futsim.partido.partido_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partido_id', 'equipo_id'),
    schema='futsim'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partido_stats_equipo', schema='futsim')
    op.drop_table('partido_contexto', schema='futsim')
    op.drop_table('partido_clima', schema='futsim')
    op.drop_table('partido', schema='futsim')
    op.drop_table('tabla_posiciones', schema='futsim')
    op.drop_table('ronda', schema='futsim')
    op.drop_table('participante', schema='futsim')
    op.drop_table('snapshot_equipo', schema='futsim')
    op.drop_table('rivalidad', schema='futsim')
    op.drop_table('ranking_entrada', schema='futsim')
    op.drop_table('historial_enfrentamiento', schema='futsim')
    op.drop_table('historia_narrativa', schema='futsim')
    op.drop_table('grupo', schema='futsim')
    op.drop_table('evento_equipo', schema='futsim')
    op.drop_table('equipo_rating_actual', schema='futsim')
    op.drop_table('equipo_institucion', schema='futsim')
    op.drop_table('equipo_finanzas', schema='futsim')
    op.drop_table('equipo_estadio_hist', schema='futsim')
    op.drop_table('equipo_elo_hist', schema='futsim')
    op.drop_table('regla_asignacion_cupos', schema='futsim')
    op.drop_table('etapa', schema='futsim')
    op.drop_table('equipo', schema='futsim')
    op.drop_table('sistema_ranking', schema='futsim')
    op.drop_table('regla_elegibilidad', schema='futsim')
    op.drop_table('regla_clasificacion', schema='futsim')
    op.drop_table('noticia', schema='futsim')
    op.drop_table('estadio', schema='futsim')
    op.drop_table('competencia_reputacion', schema='futsim')
    op.drop_table('competencia_edicion', schema='futsim')
    op.drop_table('competencia', schema='futsim')
    op.drop_table('ciudad', schema='futsim')
    op.drop_table('region', schema='futsim')
    op.drop_table('asociacion', schema='futsim')
    op.drop_table('pais', schema='futsim')
    op.drop_table('temporada', schema='futsim')
    op.drop_table('sim_log', schema='futsim')
    op.drop_table('mundo_snapshot', schema='futsim')
    op.drop_table('estadistica_global', schema='futsim')
    op.drop_table('confederacion', schema='futsim')
    op.drop_table('perfil_sorteo', schema='futsim')
    op.drop_table('perfil_climatico', schema='futsim')
    op.drop_table('mundo', schema='futsim')
    op.drop_table('media_asset', schema='futsim')
    op.drop_index(op.f('ix_futsim_cat_metodo_clasificacion_metodo_id'), table_name='cat_metodo_clasificacion', schema='futsim')
    op.drop_table('cat_metodo_clasificacion', schema='futsim')
    op.drop_index(op.f('ix_futsim_cat_etapa_tipo_tipo_id'), table_name='cat_etapa_tipo', schema='futsim')
    op.drop_table('cat_etapa_tipo', schema='futsim')
    op.drop_index(op.f('ix_futsim_cat_estado_generico_estado_id'), table_name='cat_estado_generico', schema='futsim')
    op.drop_table('cat_estado_generico', schema='futsim')
    op.drop_index(op.f('ix_futsim_cat_competencia_tipo_tipo_id'), table_name='cat_competencia_tipo', schema='futsim')
    op.drop_table('cat_competencia_tipo', schema='futsim')
    # ### end Alembic commands ###
