"""increase_participante_group_length

Revision ID: 509bb2959de3
Revises: 0da9395eac16
Create Date: 2026-02-01 20:49:04.567220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509bb2959de3'
down_revision: Union[str, Sequence[str], None] = '0da9395eac16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participante', 'grupo_inicial_texto',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True,
               schema='futsim')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participante', 'grupo_inicial_texto',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               schema='futsim')
    # ### end Alembic commands ###
