"""Increase Confederacion name length

Revision ID: bb0f848ca4d9
Revises: 509bb2959de3
Create Date: 2026-02-02 02:04:19.313957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0f848ca4d9'
down_revision: Union[str, Sequence[str], None] = '509bb2959de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('confederacion', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False,
               schema='futsim')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('confederacion', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='futsim')
    # ### end Alembic commands ###
